import React from 'react'

function About() {
  return (
    <div className='bg-slate-200'>
      <h1 className='font-semibold text-lg text-center my-10'>About</h1>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Maiores dolor quia illo laborum nesciunt ad possimus reprehenderit blanditiis dicta voluptatum corporis porro iste laudantium sint sed, repudiandae rem placeat vitae? Officia placeat a doloremque tempora aliquam alias natus esse necessitatibus ullam optio! Quos itaque quae veritatis blanditiis illo, nisi adipisci ea fugiat, hic sequi molestias, ullam dignissimos. Vel unde earum, nesciunt qui beatae consectetur, ipsa repudiandae iure soluta sunt in! Dolorem rerum totam ducimus quia ratione cupiditate voluptate placeat sed perferendis repellendus illum, tenetur consequatur saepe omnis ullam minus inventore magnam quaerat recusandae esse. Quos ducimus molestiae optio sed architecto facilis nam ullam, quod suscipit id dolores, aliquam fuga eligendi iusto nesciunt atque ipsum fugit, minima voluptates officia. Temporibus ad soluta laboriosam, dolorum officia cum voluptate commodi ex aperiam voluptatum ipsam corrupti modi porro id possimus nulla doloremque expedita. Adipisci beatae odit officia facilis sapiente. In adipisci quas non cupiditate mollitia velit laudantium, earum suscipit. Esse iste eius velit ipsam soluta possimus nemo iure odit in animi sint perferendis fuga quisquam molestiae autem, nulla, a, modi totam sed ullam tenetur quas. Nesciunt repellat enim dolorum dolor debitis ab aspernatur, autem ea ipsam ipsum fuga veritatis a quia laudantium repellendus velit, atque, voluptates labore sit. Ab rem cumque placeat accusamus repudiandae dolorum repellendus modi explicabo dolorem voluptates voluptatibus ipsam nostrum repellat quo aliquid rerum dicta expedita odio labore, delectus architecto non veniam. Culpa iusto voluptatum ipsum officia perferendis beatae doloribus autem rem nulla excepturi ducimus magnam sequi magni dolores odit necessitatibus, itaque aperiam temporibus quae omnis quo expedita tempora porro laboriosam. Minus rem maiores aspernatur voluptatum quis commodi in dicta deserunt nemo atque debitis, laboriosam iure tempore, consequuntur tenetur, culpa error quisquam facere libero sequi unde. Molestias, eveniet ullam in ducimus odit repellat iusto sint vel alias, fuga omnis minima consectetur?</p>
    </div>
  )
}

export default About